import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  await knex('badge_definitions').del();

  await knex('badge_definitions').insert([
    {
      name: 'First Post',
      name_fr: 'Premier Post',
      description: 'Shared your very first post',
      description_fr: 'Partagé ton tout premier post',
      icon: '🎨',
      category: 'social',
      xp_required: null,
      trigger_type: 'first_post',
      lumi_message: "You did it!! Your very first post!! I've been waiting for this moment! Your friends are going to LOVE hearing from you! 🎨✨",
      lumi_message_fr: "Tu l'as fait !! Ton tout premier post !! J'attendais ce moment ! Tes amis vont ADORER avoir de tes nouvelles ! 🎨✨",
    },
    {
      name: 'Kind Words',
      name_fr: 'Mots Gentils',
      description: 'Sent 5 encouraging messages',
      description_fr: 'Envoyé 5 messages encourageants',
      icon: '💛',
      category: 'kindness',
      xp_required: 5,
      trigger_type: 'encouraging_messages',
      lumi_message: "I've been watching and I have to say — you have such a kind heart. The way you encourage your friends makes Migo a better place. Never stop being you! 💛",
      lumi_message_fr: "Je t'observe et je dois dire — tu as un cœur tellement gentil. La façon dont tu encourages tes amis rend Migo meilleur. Ne change jamais ! 💛",
    },
    {
      name: 'Daily Poster',
      name_fr: 'Posteur Quotidien',
      description: 'Posted 5 days in a row',
      description_fr: 'Posté 5 jours de suite',
      icon: '📝',
      category: 'social',
      xp_required: 5,
      trigger_type: 'consecutive_posts',
      lumi_message: "5 days in a row!! Do you know how amazing that is? Your friends look forward to hearing from you every single day! 📝🌟",
      lumi_message_fr: "5 jours de suite !! Tu sais à quel point c'est incroyable ? Tes amis attendent de tes nouvelles chaque jour ! 📝🌟",
    },
    {
      name: 'Quick Learner',
      name_fr: 'Apprenant Rapide',
      description: 'Completed 3 Ms. Luna sessions',
      description_fr: 'Complété 3 séances avec Mme Luna',
      icon: '🌟',
      category: 'learning',
      xp_required: 3,
      trigger_type: 'tutor_sessions',
      lumi_message: "Ms. Luna told me you've been working SO hard! 3 sessions already — you're going to be unstoppable! 🌟📚",
      lumi_message_fr: "Mme Luna m'a dit que tu travailles tellement dur ! 3 séances déjà — tu vas être inarrêtable ! 🌟📚",
    },
    {
      name: 'Friend Maker',
      name_fr: 'Faiseur d\'Amis',
      description: 'Added 5 friends',
      description_fr: 'Ajouté 5 amis',
      icon: '🤝',
      category: 'social',
      xp_required: 5,
      trigger_type: 'friends_added',
      lumi_message: "Look at you — making friends left and right! The more the merrier on Migo! Who will you meet next? 🤝💜",
      lumi_message_fr: "Regarde-toi — tu te fais des amis à tour de bras ! Plus on est de fous, plus on rit sur Migo ! Qui vas-tu rencontrer ensuite ? 🤝💜",
    },
    {
      name: 'Chatterbox',
      name_fr: 'Bavard',
      description: 'Sent 50 messages total',
      description_fr: 'Envoyé 50 messages au total',
      icon: '💬',
      category: 'social',
      xp_required: 50,
      trigger_type: 'total_messages',
      lumi_message: "50 messages!! You are officially the best conversationalist I know! Your friends are so lucky to have someone who actually talks to them! 💬😄",
      lumi_message_fr: "50 messages !! Tu es officiellement le meilleur bavard que je connaisse ! Tes amis ont tellement de chance de t'avoir ! 💬😄",
    },
    {
      name: 'Brain Box',
      name_fr: 'Génie',
      description: 'Completed 10 Ms. Luna sessions',
      description_fr: 'Complété 10 séances avec Mme Luna',
      icon: '🧠',
      category: 'learning',
      xp_required: 10,
      trigger_type: 'tutor_sessions',
      lumi_message: "10 sessions with Ms. Luna?! You are an absolute BRAIN BOX! I am so proud of how hard you've been working! 🧠🌟",
      lumi_message_fr: "10 séances avec Mme Luna ?! Tu es un vrai génie ! Je suis tellement fier(e) de toi ! 🧠🌟",
    },
    {
      name: 'Social Star',
      name_fr: 'Star Sociale',
      description: 'Posted 20 times',
      description_fr: 'Posté 20 fois',
      icon: '🌈',
      category: 'social',
      xp_required: 20,
      trigger_type: 'total_posts',
      lumi_message: "20 posts!! You are a true Social Star — your feed is the most exciting one on Migo! Keep sharing your world with us! 🌈✨",
      lumi_message_fr: "20 posts !! Tu es une vraie Star Sociale — ton fil d'actualité est le plus excitant de Migo ! Continue à partager ton monde ! 🌈✨",
    },
    {
      name: 'Kind Heart',
      name_fr: 'Cœur Gentil',
      description: 'Reacted to 20 friend posts',
      description_fr: 'Réagi à 20 posts d\'amis',
      icon: '❤️',
      category: 'kindness',
      xp_required: 20,
      trigger_type: 'total_reactions',
      lumi_message: "You reacted to your friends' posts 20 times! Do you know how much that means to them? A simple reaction can make someone's whole day. You have a truly kind heart! ❤️",
      lumi_message_fr: "Tu as réagi aux posts de tes amis 20 fois ! Tu sais ce que ça représente pour eux ? Une simple réaction peut illuminer toute une journée. Tu as vraiment un cœur en or ! ❤️",
    },
    {
      name: 'Kind Heart',
      name_fr: 'Cœur Généreux',
      description: 'You cheered up a friend who was having a tough day',
      description_fr: "Tu as remonté le moral d'un ami qui avait une mauvaise journée",
      icon: '💜',
      category: 'kindness',
      xp_required: null,
      trigger_type: 'kind_words',
      lumi_message: "You noticed your friend was having a tough day — and you made it better. That is one of the kindest things a person can do. You have a truly warm heart 💜",
      lumi_message_fr: "Tu as remarqué que ton ami avait une mauvaise journée — et tu l'as aidé à aller mieux. C'est l'une des choses les plus gentilles qu'une personne puisse faire. Tu as vraiment un cœur généreux 💜",
    },
    {
      name: 'Graduate',
      name_fr: 'Diplômé',
      description: 'Completed the real world track',
      description_fr: 'Complété la piste du vrai monde',
      icon: '🎓',
      category: 'milestone',
      xp_required: null,
      trigger_type: 'graduation',
      lumi_message: "This is the moment I've been waiting for since the day we met. You've learned how to be a real friend online — kind, thoughtful, and safe. I am SO proud of you. You are ready for the real world! 🎓💜",
      lumi_message_fr: "C'est le moment que j'attendais depuis le jour où on s'est rencontré(e)s. Tu as appris à être un vrai ami en ligne — gentil, attentionné et sûr. Je suis TELLEMENT fier(e) de toi. Tu es prêt(e) pour le vrai monde ! 🎓💜",
    },
  ]);
}
